# Generated by Django 4.1.2 on 2024-07-23 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_group_end_date_alter_group_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
