# Generated by Django 4.1.2 on 2024-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_group_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_week',
            field=models.CharField(choices=[(2, 'Bazar Ertəsi'), (3, 'Çərşənbə Axşamı'), (4, 'Çərşənbə'), (5, 'Cümə Axşamı'), (6, 'Cümə'), (7, 'Şənbə'), (1, 'Bazar')], max_length=10, null=True),
        ),
    ]
