# Generated by Django 4.1.2 on 2024-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_group_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_week',
            field=models.CharField(choices=[('Bazar Ertəsi', 'Bazar Ertəsi'), ('Çərşənbə Axşamı', 'Çərşənbə Axşamı'), ('Çərşənbə', 'Çərşənbə'), ('Cümə Axşamı', 'Cümə Axşamı'), ('Cümə', 'Cümə'), ('Şənbə', 'Şənbə'), ('Bazar', 'Bazar')], max_length=30, null=True),
        ),
    ]
