# Generated by Django 4.1.2 on 2024-07-24 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_group_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time',
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('day_of_week', models.CharField(choices=[('Bazar Ertəsi', 'Bazar Ertəsi'), ('Çərşənbə Axşamı', 'Çərşənbə Axşamı'), ('Çərşənbə', 'Çərşənbə'), ('Cümə Axşamı', 'Cümə Axşamı'), ('Cümə', 'Cümə'), ('Şənbə', 'Şənbə'), ('Bazar', 'Bazar')], max_length=30, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teacher.group')),
            ],
        ),
    ]
