# Generated by Django 4.1.2 on 2024-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_group_day_of_week_remove_group_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
