# Generated by Django 4.1.2 on 2024-07-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_lessonschedule_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
