# Generated by Django 4.1.2 on 2024-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(default='+994', max_length=13),
        ),
        migrations.AddField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(default='+994', max_length=13),
        ),
    ]
