# Generated by Django 4.1.2 on 2024-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_student_parent_mobile_student_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
