# Generated by Django 4.1.2 on 2024-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_student_parent_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
