# Generated by Django 4.1.2 on 2024-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_student_parent_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
